
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/Tyrael/IdeaProjects/sell/var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.146.28/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.16.146.28
    port: 6379

server:
  context-path: /sell

